"""
Format a Playbook AI RunContext into a Kylon-channel-ready action pack.
"""

from __future__ import annotations

from typing import Any

from core.config import RunContext


def action_pack_markdown(ctx: RunContext) -> str:
    lines: list[str] = []
    lines.append(f"# Playbook AI action pack — {ctx.company_name or ctx.target_url}")
    lines.append("")
    lines.append(f"- **URL:** {ctx.target_url}")
    if ctx.niche:
        lines.append(f"- **Niche:** {ctx.niche}")
    if ctx.run_id:
        lines.append(f"- **Run ID:** `{ctx.run_id}`")
    lines.append(f"- **Platforms:** {', '.join(ctx.detected_platforms) or '—'}")
    lines.append("")

    conv = next(
        (f for f in ctx.findings if f.agent == "Strategist" and f.kind == "playbook"),
        None,
    )
    if conv and isinstance(conv.data, dict):
        opp = conv.data.get("biggest_opportunity")
        if opp:
            lines.append("## Biggest opportunity")
            lines.append(str(opp))
            lines.append("")
        ranked = conv.data.get("ranked_recommendations") or []
        if ranked:
            lines.append("## Ranked platforms")
            for item in ranked:
                if isinstance(item, dict):
                    lines.append(
                        f"1. **{item.get('platform')}** (p{item.get('priority')}): {item.get('why')}"
                    )
            lines.append("")

    playbooks = [
        f for f in ctx.findings if f.kind == "playbook" and f.agent != "Strategist"
    ]
    if playbooks:
        lines.append("## Per-platform playbooks")
        for pb in playbooks:
            data = pb.data or {}
            lines.append(f"### {data.get('platform') or pb.platform}")
            if data.get("cadence"):
                lines.append(f"- Cadence: {data['cadence']}")
            if data.get("gap"):
                lines.append(f"- Gap: {data['gap']}")
            wins = data.get("winning_content") or []
            if wins:
                lines.append("- Winning content:")
                for w in wins[:5]:
                    lines.append(f"  - {w}")
            lines.append("")

    outreach = [f for f in ctx.findings if f.kind == "outreach"]
    if outreach:
        lines.append("## Outreach drafts (ready to send via Kylon Gmail)")
        for o in outreach[:12]:
            d = o.data or {}
            lines.append(
                f"### {d.get('name') or 'Contact'} ({o.platform}) · {d.get('best_channel')}"
            )
            if d.get("handle"):
                lines.append(f"- Handle: {d['handle']}")
            if d.get("url"):
                lines.append(f"- Profile: {d['url']}")
            lines.append("")
            lines.append(str(d.get("draft") or ""))
            lines.append("")

    lines.append("---")
    lines.append(
        "_Generated by Playbook AI · Nimble for live web · InsForge for memory · "
        "Kylon Gmail for send._"
    )
    return "\n".join(lines)


def action_pack_json(ctx: RunContext) -> dict[str, Any]:
    return {
        "run_id": ctx.run_id,
        "company": ctx.company_name,
        "niche": ctx.niche,
        "target_url": ctx.target_url,
        "platforms": ctx.detected_platforms,
        "findings": [
            {
                "agent": f.agent,
                "platform": f.platform,
                "kind": f.kind,
                "data": f.data,
            }
            for f in ctx.findings
        ],
        "markdown": action_pack_markdown(ctx),
    }
